# Generated by Django 4.0.8 on 2022-12-11 16:28

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppBasic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('config_name', models.CharField(choices=[('AppName', 'appname'), ('Auth', 'Auth'), ('Views', 'Views')], max_length=100, unique=True)),
                ('value', models.TextField()),
                ('options', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Criteria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200)),
                ('criteria', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='DropDownFieldValues',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fieldname', models.CharField(max_length=50)),
                ('fieldvalue', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='FormsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('layout', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='CustomView',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('type', models.IntegerField(choices=[(0, 'Project'), (1, 'CR'), (2, 'Milestone'), (3, 'ResourceRequest'), (4, 'StakeHolder'), (5, 'Dependencies'), (6, 'RiskRegister')])),
                ('name', models.CharField(max_length=100)),
                ('is_default', models.BooleanField()),
                ('criteria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Setup.criteria')),
            ],
        ),
    ]
