# Generated by Django 4.0.8 on 2022-11-19 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='races',
            name='slider_logo',
            field=models.FileField(default='', upload_to=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='races',
            name='small_logo',
            field=models.FileField(default='', upload_to=''),
            preserve_default=False,
        ),
    ]
