# Generated by Django 4.0.8 on 2022-11-24 18:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_races_slider_logo_races_small_logo'),
    ]

    operations = [
        migrations.CreateModel(
            name='RaceSeries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('description', models.TextField()),
                ('logo', models.FileField(upload_to='')),
                ('slider_logo', models.FileField(upload_to='')),
                ('small_logo', models.FileField(upload_to='')),
            ],
        ),
        migrations.RemoveField(
            model_name='races',
            name='description',
        ),
        migrations.RemoveField(
            model_name='races',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='races',
            name='logo',
        ),
        migrations.RemoveField(
            model_name='races',
            name='name',
        ),
        migrations.RemoveField(
            model_name='races',
            name='slider_logo',
        ),
        migrations.RemoveField(
            model_name='races',
            name='small_logo',
        ),
        migrations.RemoveField(
            model_name='races',
            name='start_date',
        ),
        migrations.AddField(
            model_name='races',
            name='zwift_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='races',
            name='race_series',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='events.raceseries'),
        ),
    ]
