# Generated by Django 4.0.8 on 2022-11-26 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_raceseries_remove_races_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='races',
            name='name',
            field=models.CharField(default='asd', max_length=200),
            preserve_default=False,
        ),
    ]
