# Generated by Django 4.0.8 on 2022-11-26 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_zwitresult'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ZwitResult',
            new_name='ZwiftResult',
        ),
    ]
