# Generated by Django 4.0.8 on 2022-11-26 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_rename_zwitresult_zwiftresult'),
    ]

    operations = [
        migrations.AddField(
            model_name='zwiftresult',
            name='zwift_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
