# Generated by Django 4.0.8 on 2022-11-26 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_alter_zwiftresult_dt_rowid_alter_zwiftresult_actid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='races',
            name='time',
            field=models.CharField(default='1', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='zwiftresult',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Rider'),
        ),
        migrations.AlterField(
            model_name='zwiftresult',
            name='pos',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Position'),
        ),
    ]
