# Generated by Django 4.0.8 on 2022-11-27 07:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0009_races_time_alter_zwiftresult_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='races',
            name='time',
        ),
        migrations.AddField(
            model_name='races',
            name='start_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
